### ISSUE TITLE
Callback "Jump" error

### ISSUE THREAD

**Issue by scazzy** [drien/jquery-flipster#40]
![image](https://cloud.githubusercontent.com/assets/1681586/4540109/50b10dc2-4e04-11e4-90d5-08c6380274cf.png)

Cannot read property 'length' of undefined // flipster.js:267

**Comment by shshaw** [comment]
This issue should be resolved in version 1.0. Please test it out and let us know if you have any issues!

**Comment by Samiam519** [comment]
![image](https://user-images.githubusercontent.com/6751160/54720099-30bb5500-4b24-11e9-97ba-a28c1eb8bfc8.png)
Am still receiving this error with the latest release of repo. I'm manually calling jump after flipster has been initialized. I'm using jquery version 3-2-1
